sonar.organization=recmedia
sonar.projectKey=solarssk_drive-scanner-bridge
sonar.sources=uploader/scanner_drive_bridge
sonar.tests=uploader/tests
sonar.python.version=3.11
sonar.python.coverage.reportPaths=uploader/coverage.xml
